import React from "react";
import {BrowserRouter as Router} from "react-router-dom";
import {render} from "@testing-library/react";
import {InitiativeDirectory} from "src/pages/initiatives";

test("renders explanation text", () => {
  const {getByText} = render(
    <Router>
      <InitiativeDirectory />
    </Router>
  );
  const element = getByText(
    "The table below is generated by scraping Facebook once a day.",
    {exact: false}
  );
  expect(element).toBeInTheDocument();
});

test("renders first item in latest.json", () => {
  const {getByText} = render(
    <Router>
      <InitiativeDirectory />
    </Router>
  );
  const element = getByText("Alabama Face Mask Warriors");
  expect(element).toBeInTheDocument();
});
