import React from "react";
import moment from "moment";
import { Table } from "../../components/table";
import data from "../../latest.json";
import "./style.css";
import { Link } from "react-router-dom";

const columns = [
  {
    key: "_id",
    name: "Mongo ID",
    display: false,
  },
  {
    key: "id",
    name: "ID",
    display: false,
  },
  {
    key: "scrapeID",
    name: "Scrape Batch ID",
    display: false,
  },
  {
    key: "scrapedAt",
    name: "Last Updated",
  },
  {
    key: "name",
    name: "Name",
  },
  {
    key: "isPublic",
    name: "Public",
  },
  {
    key: "foundedOn",
    name: "Created",
  },
  {
    key: "description",
    name: "Description",
  },
  {
    key: "locations",
    name: "Locations",
  },
  {
    key: "memberCount",
    name: "Members",
  },
  {
    key: "memberCountIncreaseWeekly",
    name: "Weekly Growth",
  },
  {
    key: "postCountIncreaseDaily",
    name: "Daily Posts",
  },
  {
    key: "postCountIncreaseMonthly",
    name: "Monthly Posts",
  },
];

const filter = (input: string) => {
  const MIN_LENGTH = 30;
  if (input === "Public") return undefined;
  if (input.length < MIN_LENGTH) return undefined;
  return input;
};

const shorten = (input: string) => {
  const MAX_LENGTH = 100;
  if (input.length > MAX_LENGTH) return input.slice(0, MAX_LENGTH) + "...";
  return input;
};

export const InitiativeDirectory = () => (
  <div className="directory">
    <h1>PPE Initiative Directory</h1>
    <p>
      The table below is generated by scraping Facebook once a day. If you dont
      see an initiative, <Link to="/initiatives/submit">add it here</Link>.{" "}
      <strong>
        Please submit any and all initiatives, not just those on Facebook.
      </strong>
    </p>
    <Table
      columns={columns.filter((col) => col.display !== false)}
      data={data.map((entry) => ({
        ...entry,
        description: filter(shorten(entry.description)),
        foundedOn: moment(entry.foundedOn).format("YYYY-MM-DD"),
        scrapedAt: moment(entry.scrapedAt).fromNow(),
        isPublic: entry.isPublic ? "Yes" : "No",
      }))}
    />
  </div>
);
